twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
#      ville: '@App\Repository\VilleRepository'
#      contact: '@App\Repository\ContactRepository'
#      article: '@App\Manager\TagsManager'
